### ISSUE TITLE
Possible to disable nsfw commands?

### ISSUE THREAD

**Issue by ru-ni** [nitros12/LoliBot-Hy#2]
So I've got a server I want to use the markov chain bits on, and the other commands sounds like they'd get some use too but we've decided against a nsfw channel as it's typically a younger demographic.

Is it possible to just turn those bits off or will i have to daisy-chain another bot to watch for people trying to use the nsfw commands?

**Comment by ru-ni** [comment]
This was premature, it looks like it only posts NSFW stuff if the channel is tagged as such. I think i was reading from https://bots.discord.pw/bots/226409882960658432 lmao

**Comment by nitros12** [comment]
Yes, all nsfw commands will only work on nsfw channels. Additionally the gimage and booru command will toggle nsfw per channel.
